version: '3.3'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "5000:5000"
    container_name: yaits_service
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_HOST: yaits_database
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root
      SECRET_KEY: 'you-will-never-guess'

  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: yaits_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  mysql_data: